### ISSUE TITLE
  TypeError: Cannot read property 'fullscreenchange' of undefined

### ISSUE THREAD

**Issue by SpawnAtis** [brunob/leaflet.fullscreen#96] opened 2021-11-17 08:44 UTC
Hi .When I upgraded from v1.6.0 to 2.0.0 I got this error. It is reproducible only in Jest unit tests 
`  TypeError: Cannot read property 'fullscreenchange' of undefined`

**Comment by brunob** [comment] 2021-11-17 08:50
So you can't reproduce it in an example file ? If this happen only in a specific test environment, i can't help you without more information.

**Comment by brunob** [comment] 2021-12-09 19:34
No feedback, closing, feel free to comment if needed.

**Closed by brunob** 2021-12-09 19:34 UTC
Labels: question

**Comment by AMarquis1** [comment] 2022-07-28 18:30
@SpawnAtis I'm having the same issue, how did you fix it?
