### ISSUE TITLE
How to get a modal dialog work in full screen mode?

### ISSUE THREAD

**Issue by cliren** [brunob/leaflet.fullscreen#39] opened 2015-04-02 15:06 UTC
I am using a bootstrap modal dialog, it doesn't show up in full screen mode. Any suggestions on how to make it visible in full screen mode?

**Comment by brunob** [comment] 2015-04-03 07:33
sorry but i really don't know since i'm not using bootstrap. You should search around z-index rules on your modal...

Closing, cause the problem is more about bootstrap+fullscreen than this script.

**Closed by brunob** 2015-04-03 07:33 UTC

**Comment by ventralnet** [comment] 2017-06-13 15:19
If you are using angular bootstrap modal, you can use the 'appendTo' option to specify to specify an element to append to.  In this case you want to append the modal to your map div.  By default the modal is appended to the body element.  This should resolve your issue..
